export const BOOKING_JOB = {
  REMINDER: 'BOOKING_REMINDER',
  AUTO_EXPIRE: 'AUTO_EXPIRE_BOOKING',
  AUTO_COMPLETE: 'AUTO_COMPLETE_BOOKING',
} as const;

export const EMAIL_JOB = {
  CONFIRMATION: 'BOOKING_CONFIRMATION',
  CANCELLATION: 'BOOKING_CANCELLATION',
  ADMIN_NEW_CAFE_PENDING: 'ADMIN_NEW_CAFE_PENDING',
  REMINDER: 'BOOKING_REMINDER',
  VERIFICATION: 'SEND_VERIFICATION_EMAIL',
  SUSPENDED: 'ACCOUNT_SUSPENDED',
} as const;
